spring.application.name=conectaai-vrs

#Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/conectaai-vrs
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#log
logbook.format.style=http
logging.level.org.zalando.logbook=TRACE

#pageble
spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=10

api.security.token.secret=${JWT_SECRET:12345678}
api.security.cors.origins=${CORS_ORIGINS:http://localhost:5173}