spring.application.name=conectaai-vrs

#Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/conectaai-vrs
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:12345678}