spring.application.name=conectaai-vrs

#Banco de dados
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/conectaai-vrs}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#log
logbook.format.style=http
logging.level.org.zalando.logbook=TRACE

#pageble
spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=10

# Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

api.security.token.secret=${JWT_SECRET:12345678}
api.security.cors.origins=${CORS_ORIGINS:http://localhost:5173}
google.oauth.client.id=${GOOGLE_CLIENT_ID:123}
google.oauth.client.secret=${GOOGLE_CLIENT_SECRET:123}

#AWS S3
aws.s3.access-key=${AWS_ACCESS_KEY:123}
aws.s3.secret-key=${AWS_SECRET_KEY:123}
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:s3-conectaai}
aws.cloudfront.domain-name=${AWS_CLOUDFRONT_DOMAIN_NAME:d38sp318d0ruxp.cloudfront.net}

# Cookie Refresh Token
app.security.cookie.name=refreshToken
app.security.cookie.max-age=604800
app.security.cookie.secure=${COOKIE_SECURE:false}
app.security.cookie.same-site=Lax
app.security.cookie.path=/auth